# Cinfigured to match ReDroid, with a little extra padding for "window decorations", a common use case: https://github.com/remote-android/redroid-doc?tab=readme-ov-file#configuration
width: 1284
height: 740
bit_per_pixel: 16 #32

start_script_template: "start_template.sh"

start_script_path: "{{ bin_dir }}/start_{{ env_desktop | lower }}.sh"

distrobox_run_script: "distrobox enter {{ container_name_distrobox }} -- sh"

start_x11vnc: "{{ distrobox_run_script }} {{ start_script_path }}"