width: 1024
height: 768
bit_per_pixel: 16

desktop: "/usr/bin/fluxbox"

start_script: "start_x11vnc.sh"

start_script_path: "{{ bin_dir }}/{{ start_script }}"

distrobox_run_script: "distrobox enter {{ container_name_distrobox }} -- sh"

start_x11vnc: "{{ distrobox_run_script }} {{ start_script_path }}"