vnc_connection: "127.0.0.1"

vncviewer: "connect_vncviewer.sh"

vncviewer_path: "{{ bin_dir }}/{{ vncviewer }}"

Remmina: "connect_Remmina.sh"

Remmina_path: "{{ bin_dir }}/{{ Remmina }}"

distrobox_command: "distrobox enter {{ container_name_distrobox }} -- sh"

start_vncviewer: "{{ distrobox_command }} {{ vncviewer_path }}"

start_Remmina: "{{ distrobox_command }} {{ Remmina_path }}"