- name: template start_X11vnc
  ansible.builtin.template:
    src: "{{ start_script }}.j2"
    dest: "{{ start_script_path }}"
    mode: '0755'

- name: Run start_X11vnc
  ansible.builtin.shell: "distrobox enter {{ container_name_distrobox }} -- sh {{ start_script_path }}"
  async: 3600
  poll: 15
  when: not debug

- debug:
    msg: "distrobox enter {{ container_name_distrobox }} -- sh {{ start_script_path }}"
  when: debug