- name: include Env vars
  ansible.builtin.include_vars: "{{ role_path | dirname | dirname }}/Env/{{ env_desktop }}/vars/main.yml"

- name: template start_X11vnc
  ansible.builtin.template:
    src: "{{ start_script_template }}.j2"
    dest: "{{ start_script_path }}"
    mode: '0755'

- name: Run start_X11vnc
  ansible.builtin.shell: "{{ start_x11vnc }}"
  async: 3600
  poll: 15
  when: not debug

- debug:
    msg: "{{ start_x11vnc }}"
  when: debug

- name: Add to .bash_history
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.bash_history"
    line: "{{ start_x11vnc }}"