- name: Run Remmina_start.sh
  ansible.builtin.shell: "{{ Remmina_start }}"
  async: 3600
  poll: 15
  when: default_viewer == "Remmina"

- name: Run vncviewer_start.sh
  ansible.builtin.shell: "{{ vncviewer_start }}"
  async: 3600
  poll: 15
  when: default_viewer == "tigervnc"