---
- name: Distrobox container exists?
  containers.podman.podman_container_info:
    name: "{{ container_name_distrobox }}"
  register: distrobox_status

- name: debug
  debug:
    msg: "Create Distrobox! {{ container_name_distrobox }} {{ distrobox_status.containers | length == 0 }}"
  when: distrobox_status.containers | length == 0 or distrobox_status.containers.0.Name != container_name_distrobox

- name: Create home directory
  ansible.builtin.file:
    path: "{{ bin_dir }}"
    state: directory
  when: separate_home_directory

- name: create Distrobox with Home Dir
  ansible.builtin.shell: "distrobox create --pull --image {{ container_image_distrobox }} --name {{ container_name_distrobox }} --home {{ container_home_dir }}"
  async: 3600
  poll: 15
  when: separate_home_directory and (distrobox_status.containers | length == 0 or distrobox_status.containers.0.Name != container_name_distrobox)
  notify: Install Ansible

- name: create Distrobox
  ansible.builtin.shell: "distrobox create --pull --image {{ container_image_distrobox }} --name {{ container_name_distrobox }}"
  async: 3600
  poll: 15
  when: not separate_home_directory and (distrobox_status.containers | length == 0 or distrobox_status.containers.0.Name != container_name_distrobox)
  notify: Install Ansible