- name: Create bin directory
  ansible.builtin.file:
    path: "{{ bin_dir }}"
    state: directory

- name: template Ansible
  ansible.builtin.template:
    src: install-Ansible.sh.j2
    dest: "{{ install_Ansible }}"
    mode: '0755'

- name: Install Ansible in Distrobox
  ansible.builtin.shell: "distrobox enter {{ container_name_distrobox }} -- sh {{ bin_dir }}/install-Ansible.sh"
  async: 3600
  poll: 15