vnc_connection: "127.0.0.1"
distrobox_run_script: "distrobox enter {{ container_name_distrobox }} -- sh"

vncviewer: "tigervnc_viewer.sh"
vncviewer_path: "{{ bin_dir }}/{{ vncviewer }}"
vncviewer_start: "{{ distrobox_run_script }} {{ vncviewer_path }}"

Remmina: "connect_Remmina.sh"
Remmina_path: "{{ bin_dir }}/{{ Remmina }}"
Remmina_start: "{{ distrobox_run_script }} {{ Remmina_path }}"

# Todo: Make this a Dictionary! for cleaner code
remmina_config_dir: ".config/remmina"
remmina_connection_dir: ".local/share/remmina"

remmina_config_file: "remmina.pref"
remmina_connection_file: group_vnc_quick-connect_127-0-0-1.remmina

remmina_config_path: "{{ container_home_dir }}/{{ remmina_config_dir}}/{{ remmina_config_file }}"
remmina_connection_path: "{{ container_home_dir }}/{{ remmina_connection_dir }}/{{ remmina_connection_file }}"