- hosts: test #, localhost #, fedora, ubuntu
  vars:
    debug: True
    env_desktop: LXDE # Openbox
    # debug_breakpoint: True
    ansible_become_password: u

  roles:
  - in:/container
  - .test/start